#:import SMatStrm StaticUO.SMatStrm
#:import SMixer StaticUO.SMixer
#:import SFlash StaticUO.SFlash
<OmWidget>:
    cols:1
    spacing:1
    size_hint_y:None
    size_hint:(1,1)
    size:(900,400)
    pos_hint:{'center_x': .5, 'center_y': .5}
    ActionBar:
        pos_hint:{'top':0}

        ActionView:
            ActionPrevious:
                title:'Project'
                with_previous:False
            ActionButton:
                text:'Compounds'
                on_press:root.CompPop(*args)
            ActionButton:
                text:'Thermodynamics'
                on_press:root.ThermoPop(*args)
            ActionButton:
                text:'File'
                on_release:root.filedropdown.open(*args)
            ActionButton:
                text:'Edit'
                on_release:root.editdropdown.open(*args)
            ActionButton:
                text:'Insert'
                on_release:root.insertdropdown.open(*args)
            ActionButton:
                text:'Tools'
                on_release:root.toolsdropdown.open(*args)
            ActionButton:
                text:'Utilities'
                on_release:root.utilitiesdropdown.open(*args)
            ActionButton:
                text:'Optimization'
                on_release:root.optimizationdropdown.open(*args)
            ActionButton:
                text:'Scripts'
                on_release:root.scriptsdropdown.open(*args)
            ActionButton:
                text:'Results'
                on_release:root.resultsdropdown.open(*args)
            ActionButton:
                text:'Plugins'
                on_release:root.pluginsdropdown.open(*args)
            ActionButton:
                text:'Windows'
                on_release:root.windowsdropdown.open(*args)
            ActionButton:
                text:'View'
                on_release:root.viewdropdown.open(*args)
            ActionButton:
                text:'Help'
                on_release:root.helpdropdown.open(*args)
    BoxLayout:
        size_y_hint: None
        FloatLayout:
            id:b1
            size_hint:(0.75,1)
            canvas:
                Color:
                    rgba: (1,1,1,1)
                Rectangle:
                    size: self.size
                    pos: self.pos
        BoxLayout:
            size_hint:(0.25,1)
            orientation:'vertical'

            BoxLayout:
                padding: 10
                spacing: 5
                size_hint:(1,0.9)
                SMixer:
                    on_included: root.add_but(*args)
                SMatStrm:
                    on_included: root.add_but(*args)
                SFlash:
                    on_included: root.add_but(*args)
            BoxLayout:
                size_hint:(1,0.1)
                Button:
                    text:'COM'
                    size_hint_x: 0.5
                    on_press: root.compile(*args)
                Button:
                    text:'SIM'
                    size_hint_x: 0.5
                    on_press: root.simulate(*args)






