<CustButton@Button>:
    size_hint:None,None
    background_normal:''
    background_color:(0.3,0.65,1,0)

    BoxLayout:
        id:layout
        size_hint_y:None
        size: self.parent.size
        orientation:'vertical'
        padding:4
        pos: self.parent.pos

<PLabel@Label>:
    size_hint_y:None
    height:25
    text_size: self.size
    halign: 'left'
    color:0,0,0,1
<PTextInput@TextInput>:
    size_hint_y:None
    height:25
<PButton@Button>
    size_hint_y:None
    size:100,25
    font_size:15
    background_normal:''
    background_color: 0.25,0.25,0.25,1
    canvas:
        Color:
            rgba:0,0,0,1
        Line:
            rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]

<PCheckBox@CheckBox>
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos:self.center_x-8, self.center_y-8
            size:16,16
    size_hint_x:None
    width:25


<c1PopUp>:
    title:"Properties"
    size_hint:(0.3, 1)
    auto_dismiss:True
    pos_hint:{'top':1,'right':0.3}
    id:popup
    BoxLayout:
        ScrollView:
            size_hint:1,1
            GridLayout:
                cols:1
                size_hint_y:None
                height:1000
                spacing:15
                padding:5,0
                BoxLayout:
                    size_hint_y:None
                    height:100
                    orientation: 'vertical'
                    canvas:
                        Color:
                            rgba: 0,0,0,1
                        Line:
                            rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                        Color:
                            rgba: 0.7, 0.7, 0.7, 1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        size_hint_y:None
                        height:25
                        padding:5
                        canvas:
                            Color:
                                rgba: 0,0,0,1
                            Line:
                                rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                            Color:
                                rgba: 0.5, 0.5, 0.5, 1
                            Rectangle:
                                pos:self.pos
                                size:self.size
                        PLabel:
                            text:"General"
                            halign:"center"
                    GridLayout:
                        cols:2
                        padding:5
                        PLabel:
                            id:name_label
                            text:'Object'
                        PTextInput:
                            id:name
                            font_size:12
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y:None
                    height:300
                    id:connections
                    canvas:
                        Color:
                            rgba: 0,0,0,1
                        Line:
                            rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                        Color:
                            rgba: 0.7, 0.7, 0.7, 1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        size_hint_y:None
                        height:25
                        padding:5
                        canvas:
                            Color:
                                rgba: 0,0,0,1
                            Line:
                                rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                            Color:
                                rgba: 0.5, 0.5, 0.5, 1
                            Rectangle:
                                pos:self.pos
                                size:self.size
                        PLabel:
                            text:"Connections"
                            halign:"center"
                    GridLayout:
#                                size_hint_y: 0.8
                        cols:2
                        id:first_tab
                        spacing:5
                        padding:10,5

                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y:None
                    height:100
                    canvas:
                        Color:
                            rgba: 0,0,0,1
                        Line:
                            rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                        Color:
                            rgba: 0.7, 0.7, 0.7, 1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        size_hint_y:None
                        height:25
                        padding:5
                        canvas:
                            Color:
                                rgba: 0,0,0,1
                            Line:
                                rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                            Color:
                                rgba: 0.5, 0.5, 0.5, 1
                            Rectangle:
                                pos:self.pos
                                size:self.size
                        PLabel:
                            text:"Calculation Parameters"
                            halign:"center"
                    GridLayout:
                        cols:2
                        spacing:5
                        padding:10,5
                        PLabel:
                            text:"Pressure Calculation"
                        PButton:
                            text:"Select"
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y:None
                    height:100
                    canvas:
                        Color:
                            rgba: 0,0,0,1
                        Line:
                            rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                        Color:
                            rgba: 0.7, 0.7, 0.7, 1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        size_hint_y:None
                        height:25
                        padding:5
                        canvas:
                            Color:
                                rgba: 0,0,0,1
                            Line:
                                rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                            Color:
                                rgba: 0.5, 0.5, 0.5, 1
                            Rectangle:
                                pos:self.pos
                                size:self.size
                        PLabel:
                            text:"Property Package Settings"
                            halign:"center"
                    GridLayout:
                        cols:2
                        spacing:5
                        padding:10,5
                        PLabel:
                            text:"Property Package"
                        PButton:
                            text:"Select"
                        PLabel:
                            text:"Flash Algorithm"
                        PButton:
                            text:"Select"
                Button:
                    id:submit
                    size_hint_y:None
                    height:40
                    text:'Submit'


<c2PopUp>:
    title:"Properties"
    size_hint:(0.3, 1)
    auto_dismiss:True
    pos_hint:{'top':1,'right':0.3}
    id:popup
    BoxLayout:
        ScrollView:
            size_hint:1,1
            GridLayout:
                cols:1
                size_hint_y:None
                height:1000
                spacing:15
                padding:5,0
                BoxLayout:
                    size_hint_y:None
                    height:100
                    orientation: 'vertical'
                    canvas:
                        Color:
                            rgba: 0,0,0,1
                        Line:
                            rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                        Color:
                            rgba: 0.7, 0.7, 0.7, 1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        size_hint_y:None
                        height:25
                        padding:5
                        canvas:
                            Color:
                                rgba: 0,0,0,1
                            Line:
                                rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                            Color:
                                rgba: 0.5, 0.5, 0.5, 1
                            Rectangle:
                                pos:self.pos
                                size:self.size
                        PLabel:
                            text:"General"
                            halign:"center"
                    GridLayout:
                        cols:2
                        padding:5
                        PLabel:
                            id:name_label
                            text:'Object'
                        PTextInput:
                            id:name
                            font_size:12

                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y:None
                    height:100
                    id:connections
                    canvas:
                        Color:
                            rgba: 0,0,0,1
                        Line:
                            rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                        Color:
                            rgba: 0.7, 0.7, 0.7, 1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        size_hint_y:None
                        height:25
                        padding:5
                        canvas:
                            Color:
                                rgba: 0,0,0,1
                            Line:
                                rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                            Color:
                                rgba: 0.5, 0.5, 0.5, 1
                            Rectangle:
                                pos:self.pos
                                size:self.size
                        PLabel:
                            text:"Connections"
                            halign:"center"
                    GridLayout:
                        cols:2
                        spacing:5
                        padding:10,5
                BoxLayout:
                    size_hint_y:None
                    height:500
                    TabbedPanel:
                        do_default_tab: False
                        tab_height: 30
                        TabbedPanelItem:
                            text: 'Input Data'
                            font_size:12
                            BoxLayout:
                                orientation: 'vertical'
                                size_hint_y:None
                                height:400
                                id:connections
                                canvas:
                                    Color:
                                        rgba: 0,0,0,1
                                    Line:
                                        rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
                                    Color:
                                        rgba: 0.7, 0.7, 0.7, 1
                                    Rectangle:
                                        pos:self.pos
                                        size:self.size
                                GridLayout:
                                    cols:2
                                    id:first_tab
                                    spacing:5
                                    padding:10,5
                        TabbedPanelItem:
                            text: 'Compounds'
                            font_size:12
                            BoxLayout:
                                size_hint_x:0.93
                                TabbedPanel:
                                    size_hint: 0.3,1
                                    pos_hint: {'top':1}
                                    do_default_tab: False
                                    tab_width: self.parent.width/3
                                    tab_height: 30

                                    TabbedPanelItem:
                                        font_size:12
                                        text: 'Amounts'
                                        size_hint_y:1
                                        BoxLayout:
                                            size_hint_y:1
                                            orientation:'vertical'
                                            canvas:
                                                Color:
                                                    rgb: 0.5,0.5,0.5,1
                                                Rectangle:
                                                    pos:self.pos
                                                    size:self.size
                                            BoxLayout:
                                                padding:0,10,3,10
                                                size_hint_y:0.1
                                                Label:
                                                    text:'Basis'
                                                    size_hint_x:0.3
                                                    size_hint_y:0.8
                                                    font_size:12
                                                    halign:'left'
                                                TextInput:
                                                    text : 'Mole Fractions'
                                                    size_hint_y:0.8
                                                    size_hint_x:0.5
                                                    height:25
                                                    valign:'middle'
                                                    font_size:12
                                                    multiline:False
                                            BoxLayout:
                                                TabbedPanel:
                                                    size_hint: 0.3,1
                                                    pos_hint: {'top':1}
                                                    do_default_tab: False
                                                    tab_width: self.parent.width/3
                                                    tab_height: 20
                                                    TabbedPanelItem:
                                                        text:'Mixture'
                                                        font_size:12
                                                        GridLayout:
                                                            cols:2
                                                            size_hint_y:1
                                                            canvas:
                                                                Color:
                                                                    rgb: 0.7,0.7,0.7,1
                                                                Rectangle:
                                                                    pos:self.pos
                                                                    size:self.size
                                                            StackLayout:
                                                                id:compound_col_1
                                                                size_hint_y:1
                                                                orientation:'tb-lr'
                                                                canvas:
                                                                    Color:
                                                                        rgb: 0.2,0.2,0.2,1
                                                                    Rectangle:
                                                                        pos:self.pos
                                                                        size:self.size
                                                                Label:
                                                                    text:'Compound'
                                                                    size_hint_x:1
                                                                    size_hint_y:None
                                                                    font_size:12
                                                                    size:(0,20)
                                                                    color: 0, 0, 0, 1
                                                                    canvas.before:
                                                                        Color:
                                                                            rgb: 0.9,0.9,0.9,1
                                                                        Rectangle:
                                                                            pos:self.pos
                                                                            size:self.size
                                                            StackLayout:
                                                                id:compound_col_2
                                                                size_hint_y:1
                                                                orientation:'tb-lr'
                                                                canvas:
                                                                    Color:
                                                                        rgb: 0.7,0.7,0.7,1
                                                                    Rectangle:
                                                                        pos:self.pos
                                                                        size:self.size
                                                                Label:
                                                                    text:'Amount'
                                                                    size_hint_x:1
                                                                    size_hint_y:None
                                                                    size:(0,20)
                                                                    color: 0, 0, 0, 1
                                                                    font_size:12
                                                                    canvas.before:
                                                                        Color:
                                                                            rgb: 0.9,0.9,0.9,1
                                                                        Rectangle:
                                                                            pos:self.pos
                                                                            size:self.size


                                                    TabbedPanelItem:
                                                        text:'Vapor'
                                                        font_size:12
                                                        BoxLayout:
                                                            size_hint_y:1
                                                            canvas:
                                                                Color:
                                                                    rgb: 0.7,0.7,0.7,1
                                                                Rectangle:
                                                                    pos:self.pos
                                                                    size:self.size


                                    TabbedPanelItem:
                                        text: 'Properties'
                                        font_size:12
                                        size_hint_y:1
                                        BoxLayout:
                                            size_hint_y:1
                                            orientation:'vertical'
                                            canvas:
                                                Color:
                                                    rgb: 0.5,0.5,0.5,1
                                                Rectangle:
                                                    pos:self.pos
                                                    size:self.size
                                            BoxLayout:
                                                padding:0,10,3,10
                                                size_hint_y:0.1
                                                Label:
                                                    text:'Property'
                                                    font_size:12
                                                    size_hint_x:0.3
                                                    size_hint_y:0.8
                                                    halign:'left'
                                                TextInput:
                                                    text : 'Fugacity Coefficient'
                                                    size_hint_y:0.8
                                                    size_hint_x:0.5
                                                    height:25
                                                    valign:'middle'
                                                    font_size:12
                                                    multiline:False
                                            BoxLayout:
                                                TabbedPanel:
                                                    size_hint: 0.3,1
                                                    pos_hint: {'top':1}
                                                    do_default_tab: False
                                                    tab_width: self.parent.width/3
                                                    tab_height: 20
                                                    TabbedPanelItem:
                                                        font_size:12
                                                        text:'Vapour'
                                                        BoxLayout:
                                                            size_hint_y:1
                                                            canvas:
                                                                Color:
                                                                    rgb: 0.7,0.7,0.7,1
                                                                Rectangle:
                                                                    pos:self.pos
                                                                    size:self.size


                        TabbedPanelItem:
                            text: 'Phase Properties'
                            font_size:12
                            BoxLayout:
                                TabbedPanel:
                                    size_hint: 0.3,1
                                    pos_hint: {'top':1}
                                    do_default_tab: False
                                    tab_width: self.parent.width/3
                                    tab_height: 20
                                    TabbedPanelItem:
                                        text:'Mixture'
                                        font_size:12
                                        BoxLayout:
                                            size_hint_y:1
                                            canvas:
                                                Color:
                                                    rgb: 0.7,0.7,0.7,1
                                                Rectangle:
                                                    pos:self.pos
                                                    size:self.size
                                    TabbedPanelItem:
                                        text:'Vapor'
                                        font_size:12
                                        BoxLayout:
                                            size_hint_y:1
                                            canvas:
                                                Color:
                                                    rgb: 0.7,0.7,0.7,1
                                                Rectangle:
                                                    pos:self.pos
                                                    size:self.size
                        TabbedPanelItem:
                            text: 'Annotations'
                            font_size:12
                Button:
                    id:submit
                    size_hint_y:None
                    height:40
                    text:'Submit'